package com.server.ud.enums

enum class NotificationType {
    // Create
    POST_CREATED,
    POST_COMMENT_CREATED,
    POST_COMMENT_REPLY_CREATED,
    WALL_CREATED,
    WALL_COMMENT_CREATED,
    WALL_COMMENT_REPLY_CREATED,

    // Like
    POST_LIKED,
    POST_COMMENT_LIKED,
    POST_COMMENT_REPLY_LIKED,
    WALL_LIKED,
    WALL_COMMENT_LIKED,
    WALL_COMMENT_REPLY_LIKED,

    // Bookmark
    POST_BOOKMARKED,
    POST_COMMENT_BOOKMARKED,
    POST_COMMENT_REPLY_BOOKMARKED,
    WALL_BOOKMARKED,
    WALL_COMMENT_BOOKMARKED,
    WALL_COMMENT_REPLY_BOOKMARKED,

    // Reported
    POST_REPORTED,
    POST_COMMENT_REPORTED,
    POST_COMMENT_REPLY_REPORTED,
    WALL_REPORTED,
    WALL_COMMENT_REPORTED,
    WALL_COMMENT_REPLY_REPORTED,

    // Shared
    POST_SHARED,
    POST_COMMENT_SHARED,
    POST_COMMENT_REPLY_SHARED,
    WALL_SHARED,
    WALL_COMMENT_SHARED,
    WALL_COMMENT_REPLY_SHARED,


    USER_FOLLOWED,
    USER_PROFILE_SHARED,

}
