branch-defaults:
  master:
    environment: dukaankhata-eb-prod-app-env-prod
environment-defaults:
  WhatsappSurvey-env:
    branch: null
    repository: null
global:
  application_name: dukaankhata-eb-prod-app
  default_ec2_keyname: dukaankhata-eb-prod
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Corretto 11 running on 64bit Amazon Linux 2/3.2.6
  default_region: ap-south-1
  include_git_submodules: false
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
deploy:
  artifact: build/libs/dukaankhata-server-0.0.1-SNAPSHOT.jar
