server:
  port: 5000
algolia:
  application-id: ${ALGOLIA_APPLICATION_ID}
  api-key: ${ALGOLIA_API_KEY}
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
datastax:
  astra:
    secure-connect-bundle-s3-bucket: ${ASTRA_DB_BUNDLE_S3_BUCKET}
    secure-connect-bundle-s3-key: ${ASTRA_DB_BUNDLE_S3_KEY}
multipart:
  enabled: true
spring:
  http:
    multipart:
      max-request-size: 500000KB
      max-file-size: 500000KB
  data:
    cassandra:
      keyspace-name: ${ASTRA_DB_KEYSPACE}
#      username: ${ASTRA_DB_USERNAME}
#      password: ${ASTRA_DB_PASSWORD}
#      # Create the schema on the fly if it doesn't exist
      schema-action: CREATE_IF_NOT_EXISTS
      # Increase timeouts when connecting to Astra from a dev workstation
      request:
        timeout: 20s
      connection:
        connect-timeout: 20s
        init-query-timeout: 20s
  quartz:
    jdbc:
      initialize-schema: NEVER
    job-store-type: JDBC
    scheduler-name: SchedulerService
    overwrite-existing-jobs: false
  datasource:
    password: ${RDS_PASSWORD}
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
#  flyway:
#    baseline-on-migrate: true
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

security:
  firebase-props:
    database-url: https://letsunboxapp.firebaseio.com
    storage-bucket: letsunboxapp.appspot.com
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: //localhost:8080
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:8080
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
    - x-amz-sns-message-type
    - x-amz-sns-message-id
    - x-amz-sns-topic-arn
    - Content-Length
    - Host
    - Connection
    - User-Agent
  allowed-public-apis:
    - /swagger-ui.html
    - /swagger-resources/*
    - /webjars/*
    - /documentation/*
    - /actuator/*
    - /error/*
    - /favicon.ico
    - /session/login
    - /public/*
    - /seoData/*
    - /auth/*
    - /consumeAPI/*
  exposed-headers:
    - X-Xsrf-Token

notification:
  email-properties:
#    sendgrid-api-key: ${SENDGRID_API_KEY}
#    reply-to: ${REPLY_TO_EMAIL}

aws:
  account-id: ${AWS_ACCOUNT_ID}
  aws-key: ${AWS_KEY}
  aws-secret: ${AWS_SECRET}
  amplify:
    well-known-issuer: ${AMPLIFY_WELL_KNOWN_ISSUER}
    well-known-url-endpoint: ${AMPLIFY_WELL_KNOWN_ENDPOINT}
  es:
    host: ${AWS_ES_HOST}
    port: ${AWS_ES_PORT}
    protocol: ${AWS_ES_PROTOCOL}
    username: ${AWS_ES_USERNAME}
    password: ${AWS_ES_PASSWORD}
  keyspace:
    name: ${AWS_KEYSPACE_NAME}
    username: ${AWS_KEYSPACE_USERNAME}
    password: ${AWS_KEYSPACE_PASSWORD}
  sqs:
    region: ${AWS_SQS_REGION}
    queue-name: ${AWS_SQS_QUEUE_NAME}
    queue-url: "https://sqs.${AWS_SQS_REGION}.amazonaws.com/${AWS_ACCOUNT_ID}/${AWS_SQS_QUEUE_NAME}"

cloud:
  aws:
    region:
      auto: false
      static: ap-south-1
    stack:
      auto: false

payments:
  razorpay:
    key: ${RAZORPAY_KEY}
    secret: ${RAZORPAY_SECRET}

root:
  base-url: ${ROOT_BASE_URL}

sentry:
  dsn: https://4101b54301334eca9fe6dd47a3618ee9@o412876.ingest.sentry.io/5694776
  send-default-pii: true

logging:
  level:
    org.zalando.logbook: TRACE

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}

unsplash:
  client-id: ${UNSPLASH_CLIENT_ID}
  access-key: ${UNSPLASH_ACCESS_KEY}
  secret-key: ${UNSPLASH_SECRET_KEY}

pdf:
  salary-slip:
    template-name: salary_slip
    variable-name: salarySlip

management:
  metrics:
    export:
      datadog:
        api-key: ${DATADOG_API_KEY}
        app-key: ${DATADOG_APP_KEY}
        step: 20s
