security:
  cookie-props:
    domain: ${DOMAIN}
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - https://${SERVER_DOMAIN}
    - https://${CONSOLE_DOMAIN}
    - http://${LOCAL_WEB_DEV}
  allowed-origin-patterns:
    - https://*.vercel.app
