security:
  cookie-props:
    domain: ${DOMAIN}
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - https://${SERVER_DOMAIN}
  allowed-origin-patterns:
    - https://*.${vercel.app}
