package com.dukaankhata.server.enums

enum class PaymentType {
    PAYMENT_ONE_TIME_PAID,
    PAYMENT_ONE_TIME_TOOK,
    PAYMENT_ALLOWANCE,
    PAYMENT_BONUS,
    PAYMENT_DEDUCTIONS,
    PAYMENT_LOAN,
    PAYMENT_ATTENDANCE_LATE_FINE,
    PAYMENT_ATTENDANCE_OVERTIME,
    PAYMENT_OPENING_BALANCE_ADVANCE,
    PAYMENT_OPENING_BALANCE_PENDING,
    PAYMENT_SALARY,
    NONE,
}
