name: PR Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Copy jar to root
        uses: canastro/copy-action@0.0.2
        with:
          source: build/libs/dukaankhata-server-0.0.1-SNAPSHOT.jar
          target: .
      - name: Create a folder to store zip file
        run: mkdir release-zip
      - name: Zip the jar
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -r ./release-zip/release.zip ./dukaankhata-server-0.0.1-SNAPSHOT.jar ./.ebextensions
      - name: Get Time for version label
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 8
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Check if the Time for version label is correctly prining in the build terminal
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME

